# Generated by Django 4.0.4 on 2022-05-25 04:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('shorttext', models.CharField(max_length=150, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
