# Generated by Django 4.0.4 on 2022-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_categoryimg_postimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
