# Generated by Django 4.0.4 on 2022-06-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_imgname_categoryimg_catname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimg',
            old_name='catName',
            new_name='imgName',
        ),
    ]
