# Generated by Django 4.0.4 on 2022-06-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_catname_categoryimg_imgname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimg',
            old_name='cat_id',
            new_name='cat_img',
        ),
    ]
