# Generated by Django 4.0.4 on 2022-06-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_cat_id_postimg_cat_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimg',
            old_name='cat_img',
            new_name='cat_id',
        ),
    ]
